//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalProject.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags.
        /// </summary>
        public static string AddTags {
            get {
                return ResourceManager.GetString("AddTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of postcards.
        /// </summary>
        public static string AmountOfPostcards {
            get {
                return ResourceManager.GetString("AmountOfPostcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string AnErrorOccurredWhileProcessingYourRequest {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileProcessingYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string Animals {
            get {
                return ResourceManager.GetString("Animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account.
        /// </summary>
        public static string AssociateYour_Account {
            get {
                return ResourceManager.GetString("AssociateYour_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average rating.
        /// </summary>
        public static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with category is required.
        /// </summary>
        public static string CategoryRequired {
            get {
                return ResourceManager.GetString("CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your data.
        /// </summary>
        public static string ChangeYourData {
            get {
                return ResourceManager.GetString("ChangeYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a postcard.
        /// </summary>
        public static string CreateAPostcard {
            get {
                return ResourceManager.GetString("CreateAPostcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 15 high ratings.
        /// </summary>
        public static string ForFifteenHighRatings {
            get {
                return ResourceManager.GetString("ForFifteenHighRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 15 likes.
        /// </summary>
        public static string ForFifteenLikes {
            get {
                return ResourceManager.GetString("ForFifteenLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 5 high ratings.
        /// </summary>
        public static string ForFiveHighRatings {
            get {
                return ResourceManager.GetString("ForFiveHighRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 5 likes.
        /// </summary>
        public static string ForFiveLikes {
            get {
                return ResourceManager.GetString("ForFiveLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 10 high ratings.
        /// </summary>
        public static string ForTenHighRatings {
            get {
                return ResourceManager.GetString("ForTenHighRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 10 likes.
        /// </summary>
        public static string ForTenLikes {
            get {
                return ResourceManager.GetString("ForTenLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray and green.
        /// </summary>
        public static string GrayAndGreen {
            get {
                return ResourceManager.GetString("GrayAndGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} format is not correct.
        /// </summary>
        public static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string LogInUsingYour_Account {
            get {
                return ResourceManager.GetString("LogInUsingYour_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirmation password do not match.
        /// </summary>
        public static string NewPasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comments.
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation password do not match.
        /// </summary>
        public static string PasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcard.
        /// </summary>
        public static string Postcard {
            get {
                return ResourceManager.GetString("Postcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcards with tag.
        /// </summary>
        public static string PostcardsWithTag {
            get {
                return ResourceManager.GetString("PostcardsWithTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with {0}. Please enter an email for this site below and click the {1} button to finish logging in..
        /// </summary>
        public static string RegisterAuthenticatedAccount {
            get {
                return ResourceManager.GetString("RegisterAuthenticatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a template.
        /// </summary>
        public static string SelectTemplate {
            get {
                return ResourceManager.GetString("SelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {2} characters long.
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 lately added.
        /// </summary>
        public static string TenLatelyAdded {
            get {
                return ResourceManager.GetString("TenLatelyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no image with given id.
        /// </summary>
        public static string ThereAreNoImageWithGivenId {
            get {
                return ResourceManager.GetString("ThereAreNoImageWithGivenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such hashtags.
        /// </summary>
        public static string ThereIsNoSuchHashTags {
            get {
                return ResourceManager.GetString("ThereIsNoSuchHashTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not your postcard.
        /// </summary>
        public static string ThisIsNotYourPostcard {
            get {
                return ResourceManager.GetString("ThisIsNotYourPostcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5.
        /// </summary>
        public static string TopFive {
            get {
                return ResourceManager.GetString("TopFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an image.
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in.
        /// </summary>
        public static string UseALocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in.
        /// </summary>
        public static string UseAnotherServiceToLogIn {
            get {
                return ResourceManager.GetString("UseAnotherServiceToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist.
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet and beige.
        /// </summary>
        public static string VioletAndBeige {
            get {
                return ResourceManager.GetString("VioletAndBeige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VK.
        /// </summary>
        public static string Vkontakte {
            get {
                return ResourceManager.GetString("Vkontakte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t enter anything.
        /// </summary>
        public static string YouDidNotEnterAnything {
            get {
                return ResourceManager.GetString("YouDidNotEnterAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t enter a hash tag.
        /// </summary>
        public static string YouDidNotEnterHashTag {
            get {
                return ResourceManager.GetString("YouDidNotEnterHashTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t enter postcard id.
        /// </summary>
        public static string YouDidNotEnterPostcardId {
            get {
                return ResourceManager.GetString("YouDidNotEnterPostcardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t enter user&apos;s id.
        /// </summary>
        public static string YouDidNotEnterUserId {
            get {
                return ResourceManager.GetString("YouDidNotEnterUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment.
        /// </summary>
        public static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your postcard was successfully deleted.
        /// </summary>
        public static string YourPostcardWasSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("YourPostcardWasSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your postcard was successfully saved.
        /// </summary>
        public static string YourPostcardWasSuccessfullySaved {
            get {
                return ResourceManager.GetString("YourPostcardWasSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rating was successfully changed.
        /// </summary>
        public static string YourRatingWasSuccessfullyChanged {
            get {
                return ResourceManager.GetString("YourRatingWasSuccessfullyChanged", resourceCulture);
            }
        }
    }
}
